server:
  port: 8135
  servlet:
    context-path: /sdf
  tomcat:
    max-threads: 300
    min-spare-threads: 200
    accept-count: 100
    connection-timeout: 5000

spring:
  datasource:
    url: jdbc:mysql://134.175.103.104/jdbc?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
    druid:
      initial-size: 5   #初始化连接个数
      min-idle: 5       #最小连接个数
      max-active: 20    #最大连接个数
      max-wait: 6000    #最大等待时间
      stat-view-servlet:
        enabled: true
      web-stat-filter:
        enabled: true
      aop-patterns: com.sdf.demo.serviceImpl.*